/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

module.exports = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  // Infrastructure: ['Docs/Infrastructure'],
  Docs: {
    docs: ['Docs/web2', 'Docs/what', 'Docs/why'],
  },
  css: {
    前言: ['css/css-intro'],
    css基础: ['css/css基础/test/css-test'],
  },
  react3333333: {
    前言111: ['react/react-intro'],
    react基础: [
      'react/react基础/test/react-test',
      'react/react基础/test/react-test2',
    ],
  },

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['hello'],
    },
  ],
   */
}
